GAME_STATUS_MAINMENU = 0
GAME_STATUS_COUNTDOWN = 1
GAME_STATUS_PLAYING = 4
GAME_STATUS_SCORE = 100
GAME_SPEED_FACTOR = .5

# Player
PLAYER_MINIMUM_SPEED = 7
PLAYER_MAXIMUM_SPEED = 10
PLAYER_SPEED_FACTOR = 1.5

# Score
AREA_TO_SCORE_RATIO = 2
